name: flutter_katalog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Tambahkan baris provider ini agar state management berjalan:
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Bagian assets sudah benar (pastikan nama folder di proyekmu adalah 'assets'):
  assets:
    - assets/